### PR TITLE
Needed to update the permissions on the .dll files to be executable.

### PR DESCRIPTION
**Pull request by tiffanycmeyer13**

### CODE REVIEW

**Comment by srcarter3** [comment]
This is just a windows change, and so I think it should probably go in a windows branch (no?)

**Comment by tiffanycmeyer13** [comment]
I think it's more than reasonable to keep it in the main branch. The package already exists in the main branch, I just had to change the permissions. The less branches, the better and since this has no effect on Mac or Linux then I think it can stay here.

**Comment by srcarter3** [comment]
Okay, has it been tested on mac and linux?

**Comment by tiffanycmeyer13** [comment]
This has been tested on linux with the latest rpms with no issues

**Pull request merged**
